version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda:18.04-5.2
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.2-bionic"

  test:
    image: swift-aws-lambda:18.04-5.2

  shell:
    image: swift-aws-lambda:18.04-5.2
