version = 0.1
[default.deploy.parameters]
stack_name = "StreamingNumbers"
resolve_s3 = true
s3_prefix = "StreamingNumbers"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
